name:                interp
version:             0.1.0.0
github:              "darkey91/interp"
license:             BSD3
author:              "Diana Kudaiberdieva"
maintainer:          "eglet91@gmail.com"
copyright:           "2020 Diana Kudaiberdieva"

extra-source-files:
- README.md
- ChangeLog.md
- src/Parser/PascalLexer.x
- src/Parser/PascalParser.y


# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/darkey91/interp#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - array
    - mtl
    - containers

executables:
  interp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - interp
    - pretty-simple

tests:
  interp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -Wall
    - -with-rtsopts=-N
    dependencies:
    - interp
    - hspec
